name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
      slack_channel:
        description: 'Slack Channel'
        required: false

jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set Git user Info
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Grant scripts permission
        run: |
          chmod +x ./scripts/release/hotfix_release/update_sdk_version.sh
      - name: Create Release Branch
        shell: bash
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          ./scripts/release/hotfix_release/update_sdk_version.sh ${{ github.event.inputs.version }}
          git add --all
          git status
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Release ${{ github.event.inputs.version }}"
          fi
          git status
          
          git checkout -b release/${{ github.event.inputs.version }}
          git push -u origin release/${{ github.event.inputs.version }}
