name: Build regression tester and notify on Slack

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
      slack_channel:
        description: 'Slack Channel'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 1.8
# Commit & push, make sure the  release-candidate job running after every push builds the release candidate successfully
# Upload to private git using this job with the release candidate number added to the S3_BUILD_NUMBER job parameter
      - name: Upload to private git using this job with the release candidate number added to the S3_BUILD_NUMBER job parameter
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email '

      - name: Build Regression Tester
        run: |
          echo "Building Regression Tester"

  notify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: message
          custom_payload: |
            {
              "text": "Workflow dispatched",
              "channel": "${{ github.event.inputs.slack_channel }}",
              "attachments": [{
                "text": "Regression tester version: $SDK_VERSION was released list of the features"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

