name: Create Release branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
      slack_channel:
        description: 'Slack Channel'
        required: false

jobs:
  release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant scripts permission
        run: |
          chmod +x ./scripts/release/hotfix_release/update_sdk_version.sh
      - name: Create Release Branch
        shell: bash
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          ./scripts/release/hotfix_release/update_sdk_version.sh ${{ github.event.inputs.version }}
          git add --all
          git status
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Release ${{ github.event.inputs.version }}"
          fi
          git status
          
          git checkout -b release/${{ github.event.inputs.version }}
          git push -u origin release/${{ github.event.inputs.version }}

      - name: Prepare Slack Message
        if: success() && ${{ github.event.inputs.slack_channel != '' }}
        run: |
          slack_message="* Created branch for release version:* ${{ env.ADAPTER_VERSION }}"
          echo 'slack-message<<EOF' >> $GITHUB_OUTPUT
          echo "$slack_message" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Publish Slack Message
        uses: rtCamp/action-slack-notify@v2
        if: success() && ${{ github.event.inputs.slack_channel != '' }}
        env:
          SLACK_CHANNEL: ${{ github.event.inputs.slack_channel }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://pbs.twimg.com/profile_images/1079318741140287488/o-dkhgcc_400x400.jpg
          SLACK_TITLE: 'Release branch for version: ${{ github.event.inputs.version }} !'
          SLACK_MESSAGE: ${{ steps.run_shell_script.outputs.slack-message }}
          SLACK_USERNAME: DnD_Automation
          SLACK_WEBHOOK: ${{ secrets.ADAPTERS_SLACK_WEBHOOK_URL }}
          MSG_MINIMAL: commit,actions url
#      - name: Job Summary
#        run: |
#          echo "Follow the instruction below to complete publishing the adapter" >> $GITHUB_STEP_SUMMARY
#          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
#          echo "- [ ] *update adapters excel:* https://docs.google.com/spreadsheets/d/1LVLXlCn6gwydPMMFOid40hexvk7SUTyLRLovI0spxko/edit#gid=0" >> $GITHUB_STEP_SUMMARY
#          echo "- [ ] *git branch name:* ${{ github.event.inputs.branch_name_to_publish }}" >> $GITHUB_STEP_SUMMARY
#          echo "- [ ] *git merge:* merge the pull request from here: https://github.com/ironsource-mobile/android-mediation-sdk/pulls" >> $GITHUB_STEP_SUMMARY
#          echo "- [ ] *git merge optional:* (if needed) manually merge the release branch to active release branches and notify the active release owner" >> $GITHUB_STEP_SUMMARY
